[package]
name = "gc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
once_cell = "1.12.0"
parking_lot = "0.12.1"
x86 = "0.48.0"
# aarch64 = "0.0.7"
