hard_tabs = true
tab_spaces = 8
reorder_impl_items = true
reorder_imports = true
group_imports = "StdExternalCrate"
condense_wildcard_suffixes = true
format_strings = false
imports_granularity = "Crate"
newline_style = "Unix"
